// Copyright Epic Games, Inc. All Rights Reserved.


#include "TP_WeaponComponent.h"

//#include "EnemyBase.h"
//#include "EnemyPoolManager.h"
#include "Ludens_PCharacter.h"
#include "Ludens_PProjectile.h"
#include "GameFramework/PlayerController.h"
#include "Camera/PlayerCameraManager.h"
#include "Kismet/GameplayStatics.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "Projects.h"
#include "Animation/AnimInstance.h"
#include "Camera/CameraComponent.h"
#include "Engine/LocalPlayer.h"
#include "Engine/World.h"

// Sets default values for this component's properties
// ë¬´ê¸° ì¢…ë¥˜ì™€ Fire ë©”ì„œë“œ, íƒ„ì•½, ì¬ì¥ì „ ë“± ë¬´ê¸°ì™€ ê´€ë ¨ëœ ë©”ì„œë“œë“¤
UTP_WeaponComponent::UTP_WeaponComponent()
{
	// Default offset from the character location for projectiles to spawn
	MuzzleOffset = FVector(50.0f, 100.0f, 0.0f);
}
void UTP_WeaponComponent::BeginPlay()
{
	Super::BeginPlay();

	if (!Character)
	{
		Character = Cast<ALudens_PCharacter>(GetOwner());
		if (!Character)
		{
			UE_LOG(LogTemp, Error, TEXT("WeaponComponent could not find owning character!"));
		}
	}
}

void UTP_WeaponComponent::Fire()
{
	if (!Character)
	{
		Character = Cast<ALudens_PCharacter>(GetOwner());
		if (!Character)
		{
			UE_LOG(LogTemp, Error, TEXT("âŒ Character is null"));
			return;
		}
	}

	// ìœ„ì¹˜ ë° ë°©í–¥
	FVector CameraLocation = Character->FirstPersonCameraComponent->GetComponentLocation();
	FRotator SpawnRotation = Character->GetActorRotation();
	if (APlayerController* PC = Cast<APlayerController>(Character->GetController()))
	{
		SpawnRotation = PC->PlayerCameraManager->GetCameraRotation();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("â— GetController() is null, fallback to actor rotation"));

	}
	// ì¹´ë©”ë¼ ì•ìª½ì—ì„œ ë°œì‚¬
	constexpr float Distance = 10.0f;
	FVector FireDirection = SpawnRotation.Vector();
	FVector SpawnLocation = CameraLocation + FireDirection * Distance;

	if (Character->HasAuthority())
	{
		HandleFire(SpawnLocation, SpawnRotation);
	}
	else
	{
		ServerFire(SpawnLocation, SpawnRotation);
	}
}
void UTP_WeaponComponent::ServerFire_Implementation(FVector_NetQuantize SpawnLocation, FRotator SpawnRotation)
{
	// í´ë¼ì´ì–¸íŠ¸ê°€ ìš”ì²­ â†’ ì„œë²„ì—ì„œ ì²˜ë¦¬
	HandleFire(SpawnLocation, SpawnRotation);
}
void UTP_WeaponComponent::HandleFire(const FVector& SpawnLocation, const FRotator& SpawnRotation) //ì„œë²„ì—ì„œ ì“°ëŠ” Fire (ì–˜ê°€ ì§„ì§œ Projectileì„ ì˜ëŠ”ê±°ì„)
{
	UE_LOG(LogTemp, Log, TEXT("FireFireFire"))
	if (!ProjectileClass) //í”„ë¡œì íƒ€ì¼ nullê°’ ë°©ì§€
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ ProjectileClass is null"));
		return;
	}

	if (!Character) //ìºë¦­í„° nullê°’ ë°©ì§€
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Character is null in HandleFire"));
		return;
	}

	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = GetOwner();
	SpawnParams.Instigator = Cast<APawn>(GetOwner());
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButDontSpawnIfColliding;

	ALudens_PProjectile* Projectile = GetWorld()->SpawnActor<ALudens_PProjectile>(ProjectileClass, SpawnLocation, SpawnRotation, SpawnParams); // (ìŠ¤í° ìœ„ì¹˜, ë°©í–¥, ì•¡í„°ê°€ ê²Œì„ ì›”ë“œê°€ ìŠ¤í°ë  ë•Œ ë””í…Œì•Œí•œ ë¶€ë¶„ì„ ì¡°ì • ê°€ëŠ¥.)
	if (!Projectile)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Projectile spawn failed"));
		return;
	}

	// ğŸ”Š ì„œë²„ì—ì„œë„ ì‚¬ìš´ë“œ/ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒì€ Multicast ë˜ëŠ” í´ë¼ ì „ìš©ìœ¼ë¡œ ì²˜ë¦¬ í•„ìš”

	if (FireSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, FireSound, Character->GetActorLocation());
	}

	if (FireAnimation)
	{
		UAnimInstance* AnimInstance = Character->GetMesh1P()->GetAnimInstance();
		if (AnimInstance)
		{
			AnimInstance->Montage_Play(FireAnimation, 1.f);
		}
	}
}
void UTP_WeaponComponent::EndPlay(const EEndPlayReason::Type EndPlayReason) //í•„ìš” ì—†ì„ê±°ê°™ì€ë°
{
	if (Character == nullptr)
	{
		return;
	}

	if (APlayerController* PlayerController = Cast<APlayerController>(Character->GetController()))
	{
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
		{
			Subsystem->RemoveMappingContext(FireMappingContext);
		}
	}
}